[package]
name = "wsim-data"
description = "Laden und Prüfen der WSim-Datendateien"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
saphyr-parser = "0.1"
wsim-core.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
